//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelligentAgriculture
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipment_information
    {
        public string MAC { get; set; }
        public Nullable<double> X { get; set; }
        public Nullable<double> Y { get; set; }
        public string Type { get; set; }
        public Nullable<bool> Temperature { get; set; }
        public Nullable<bool> Humidity { get; set; }
        public Nullable<bool> Pressure { get; set; }
        public Nullable<bool> Precipitation { get; set; }
        public Nullable<bool> Wind_speed { get; set; }
        public Nullable<bool> Wind_direction { get; set; }
        public Nullable<bool> Soil_temperature { get; set; }
        public Nullable<bool> Soil_water_content { get; set; }
        public Nullable<bool> Light { get; set; }
        public Nullable<bool> Dissolved_oxygen { get; set; }
        public Nullable<bool> Oxygen_density { get; set; }
        public Nullable<bool> CO2_density { get; set; }
        public Nullable<bool> Water_level { get; set; }
        public string Node_name { get; set; }
    }
}
