//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelligentAgriculture
{
    using System;
    using System.Collections.Generic;
    
    public partial class soil_moisture_10d
    {
        public int id { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string Node_ID { get; set; }
        public Nullable<double> Soil_moisture_avg { get; set; }
        public Nullable<double> Soil_moisture_min { get; set; }
        public Nullable<double> Soil_moisture_max { get; set; }
    }
}
