//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelligentAgriculture
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public string User_name { get; set; }
        public string User_password { get; set; }
        public string E_mail { get; set; }
        public string Phone { get; set; }
        public string Status { get; set; }
    }
}
